title: My Docs Site
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

markdown: kramdown

collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default


just_the_docs:
  search_enabled: true
