title: My Docs Site
remote_theme: jekyll/minima
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
